FORMAT: 1A
HOST: http://localhost:9090/gate_three-restAPI

# Gate Three API

API provides access to Gate Three services.

## Group User Session Management

Resources related to user session management.

## User Session [/usersession]

### Create User Session [POST /usersession{?idCustomer,idProject}]

Create a user session in Gate Three and logs into the specified customer and project.  The response is the user session token that is passed to all future requests in the **G3-User-Session-Token** header.

+ Parameters
    + idCustomer: 1 (string, required) - ID of customer to login to
    + idProject: 1010 (string, optional) - ID of project to login to.  Use "home" to login to **Gate Three Home**.
        + Default: home

+ Request (application/json)

    + Attributes (User Credentials)

+ Response 200 (application/json)

    + Attributes (object)
        + returnedObject (Token)
        + messages (array[Message], optional) - List of user mesages.

### Delete User Session [DELETE]

Deletes (logout) of the user session specified in the **G3-User-Session-Token** header.

+ Request

    + Header

            G3-User-Session-Token: <user-session-token>

+ Response 200 (application/json)

## Customer Login [/usersession/logInToCustomer/{idCustomer}]

In active session, logs into a different customer.  The response is the new user session token that should be used going forward in the **G3-User-Session-Token** header.

### Log into Customer [POST]

+ Parameters
    + idCustomer: 2 (string) - ID of customer to login to.

+ Request (application/json)

    + Header

            G3-User-Session-Token: <user-session-token>

+ Response 200 (application/json)

    + Attributes (object)
        + returnedObject (Token)
        + messages (array[Message], optional) - List of user mesages.

## Project Login [/usersession/logInToProject/{idProject}]

In active session, logs into a different project.  The response is the new user session token that should be used going forward in the **G3-User-Session-Token** header.

### Log into Project [POST]

+ Parameters
    + idProject: 2020 (string) - ID of project to login to.  Use "home" to login to **Gate Three Home**.

+ Request (application/json)

    + Header

            G3-User-Session-Token: <user-session-token>

+ Response 200 (application/json)

    + Attributes (object)
        + returnedObject (Token)
        + messages (array[Message], optional) - List of user mesages.

## Group Settings

Resources related to settings.

## Settings Collection [/settings]

### Get Setting [GET /settings{?name,selectedIds}]

Get values for a setting.

+ Parameters
    + name: CNF_CHANGE_TYPE (enum[string], required) - Name of setting to get
        + Members
            + AUTOMATIC_SCO_ISSUING
            + CNF_CHANGE_TYPE
            + CNF_CHANGE_TYPE_DEFAULT
            + CNF_CHANGE_TYPE_AUTO
            + CHANGE_AUTO_CREATE_BUDGET_BILLING
            + CNF_CHANGE_ISSUE_CODE
            + CNF_CHANGE_ISSUE_CODE_DEFAULT
            + CNF_CHANGE_REASON
            + CNF_CHANGE_REASON_DEFAULT
            + CNF_CHANGE_CONTACT_NOTIF
            + CNF_CHANGE_ADDITIONAL_COST
            + CNF_CHANGE_HIDE_FIELD_ALL
            + CNF_CHANGE_HIDE_FIELD_OVERHEAD
            + CNF_CHANGE_HIDE_FIELD_TAXES
            + CNF_CHANGE_HIDE_FIELD_BUDGETLINES
            + CNF_CHANGE_HIDE_FIELD_BILLINGLINES
            + QUOTE_REQUEST_NOTIFICATION
            + CHANGE_DESCRIPTION
            + ISSUE_CHANGE_ORDER_NOTIFICATION
            + ISSUE_SUB_CHANGE_ORDER_NOTIFICATION
            + CHANGE_SUBMISION_NOTIFICATION
            + PARAMETER_CHANGE_PHASE
            + PARAMETER_SUBCONTRACTEDQUOTE_OVERHEADPROFIT_PERCENTAGE
            + PARAMETER_SELFTPERFORMEDQUOTE_OVERHEADPROFIT_PERCENTAGE
            + PROGRESS_DETAILS_REVIEW_TEMPLATE
            + PROGRESS_SUMMARY_REVIEW_TEMPLATE
            + PROGRESS_DISTRIBUTION_REVIEW_TEMPLATE
            + PARAMETER_UNASSIGNEDQUOTE_OVERHEADPROFIT_PERCENTAGE
            + CHANGE_CONFIGURATION_COSTACCOUNT_SUBCONTRACTED_QUOTE
            + CHANGE_CONFIGURATION_COSTACCOUNT_SELFPERFORMED_QUOTE
            + CHANGE_CONFIGURATION_COSTACCOUNT_UNASSIGNED_QUOTE
            + CHANGE_CONFIGURATION_COSTACCOUNT_ALL
    + selectedIds: 12,578,444 (array[number], optional) - Currently selected values (only pass ID of those values).

+ Request

    + Header

            G3-User-Session-Token: <user-session-token>
            G3-Action-Context-Token: <action-context-token>

+ Response 200 (application/json)

    + Attributes (object)
        + returnedObject (array[Change Type Setting]) - Setting values.
        + messages (array[Message], optional) - List of user mesages.

## Group Access Control Privileges

Resources related to checking access control privileges.

**How privileges work**: privileges have an order.  Starting from the lowest privilege, they are: *Read*, *Update*, *Create*, and *Execute*.  Therefore if a user has the *Execute* privilege then they have full access (i.e. implies they have the lower privileges: *Read*, *Update*, and *Create*).  The *hasAccessControlRight* endpoint checks if a user has the requested privilege *or higher*.  You can specify a *strict* flag to check if they have the exact privilege.  A more convenient endpoint is the get *highestPrivilege*, which returns the highest privilege.  Therefore if you want to know if a user has edit or just read only, you can call the endpoint and test if the privilege is equal to *Read*.

## Get Highest Privilege Collection [/acp/highestPrivilege]

## Get Highest Privilege for a Group [GET /acp/highestPrivilege{?groupName}]

Retrieves the user's higheset privilege to a requested group.

+ Parameters
    + groupName: Comany Category (string) - Name of group to check if user has access.

+ Request (application/json)

    + Header

            G3-User-Session-Token: <user-session-token>
            G3-Action-Context-Token: <action-context-token>

+ Response 200 (application/json)

    + Attributes (object)
        + returnedObject (ACP Response) - Highest privilege for group.
        + messages (array[Message], optional) - List of user mesages.

## Get Highest Privileges for a List of Groups [POST /acp/highestPrivilege]

Retrieves the user's higheset privilege to a requested list of groups.

+ Request (application/json)

    + Header

            G3-User-Session-Token: <user-session-token>
            G3-Action-Context-Token: <action-context-token>

    + Attributes (array[ACP Request])

+ Response 200 (application/json)

    + Attributes (object)
        + returnedObject (array[ACP Response]) - Highest privilege for groups.
        + messages (array[Message], optional) - List of user mesages.

## Group Change Management Module

Resources related to the change management module.

## Change Document Collection [/cm/changeform]

### Open Change Document Form [GET /cm/changeform{?iddocument}]

Open a change document for viewing and editing.  In the response is the *action context* which is to be included in the *G3-Action-Context-Token* header for other requests such as retrieving settings for the requested document.

  + Parameters
      + iddocument: 1001 (number, required) - ID of change document to open.

  + Request

      + Header

              G3-User-Session-Token: <user-session-token>

  + Response 200 (application/json)

        {
          "returnedObject": {
            "changed": false,
            "obs": [],
            "saveOrUpdateCalled": false,
            "userSessionId": null,
            "userActionId": null,
            "actionContext": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFByb2plY3QiOjU1OSwiaG9tZVByb2plY3QiOmZhbHNlLCJzZXR0aW5nTGV2ZWxFbnVtIjoiUHJvamVjdCIsInNldHRpbmdUYXJnZXRJZCI6NTU5LCJhY3BNb2RlRW51bSI6IkVOVElUWV9QUk9KRUNUX1RPX1NFU1NJT05fUFJPSkVDVCIsImFjcFByb2plY3RJZCI6NTU5fQ.v88zLEb3HO09R0yA0MyILHECdI6VNZIoWm6qv7Tx8lQ",
            "userAction": "NOACTION",
            "mainDocumentBean": {
              "changed": false,
              "obs": [],
              "saveOrUpdateCalled": false,
              "userSessionId": null,
              "userActionId": null,
              "actionContext": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFByb2plY3QiOjU1OSwiaG9tZVByb2plY3QiOmZhbHNlLCJzZXR0aW5nTGV2ZWxFbnVtIjoiUHJvamVjdCIsInNldHRpbmdUYXJnZXRJZCI6NTU5LCJhY3BNb2RlRW51bSI6IkVOVElUWV9QUk9KRUNUX1RPX1NFU1NJT05fUFJPSkVDVCIsImFjcFByb2plY3RJZCI6NTU5fQ.v88zLEb3HO09R0yA0MyILHECdI6VNZIoWm6qv7Tx8lQ",
              "userAction": "NOACTION",
              "persistentDTO": {
                "idChangeDocument": 114001,
                "fkChangeReason": {
                  "idChangeReason": 200,
                  "name": null,
                  "description": "qwer2",
                  "fkAclLevel": {
                    "idAclLevel": 1,
                    "aclLevelName": "Customer",
                    "targetID": 0,
                    "createdBy": 100,
                    "createdDate": 1252472400000,
                    "updatedBy": 100,
                    "updatedDate": 1322150317000,
                    "lockVersion": 148,
                    "parentAclLevelId": null
                  },
                  "isLock": null,
                  "isDefault": true,
                  "createdBy": 0,
                  "createdDate": 1338395017000,
                  "updatedBy": 0,
                  "updatedDate": 1412280555000,
                  "lockVersion": 5,
                  "homeProject": true,
                  "activateActionAvailable": false,
                  "deactivateActionAvailable": false,
                  "deleteActionAvailable": true,
                  "editActionAvailable": true,
                  "validateEditOnSaveIfNotUsed": false
                },
                "fkChangeType": {
                  "idChangeType": 60290,
                  "isActive": true,
                  "name": null,
                  "description": "Change type Test 0004",
                  "prefix": "ZOO4",
                  "nextAvailableNumber": 3,
                  "isTotalEstimatedAmount": true,
                  "isNotToExceedAmount": true,
                  "updatePrimeContractPayApplication": true,
                  "isDrawdown": false,
                  "fkjasperTemplate": null,
                  "fkAclLevel": {
                    "idAclLevel": 1,
                    "aclLevelName": "Customer",
                    "targetID": 0,
                    "createdBy": 100,
                    "createdDate": 1252472400000,
                    "updatedBy": 100,
                    "updatedDate": 1322150317000,
                    "lockVersion": 148,
                    "parentAclLevelId": null
                  },
                  "isLock": null,
                  "isDefault": false,
                  "createdBy": 100019,
                  "createdDate": 1362581958000,
                  "updatedBy": 100019,
                  "updatedDate": 1452872312000,
                  "lockVersion": 8,
                  "homeProject": true,
                  "activateActionAvailable": false,
                  "deactivateActionAvailable": true,
                  "deleteActionAvailable": true,
                  "editActionAvailable": true,
                  "validateEditOnSaveIfNotUsed": false
                },
                "fkChangeIssueCode": {
                  "idChangeIssueCode": 3970,
                  "name": null,
                  "description": "ds2",
                  "fkAclLevel": {
                    "idAclLevel": 8484,
                    "aclLevelName": "Project",
                    "targetID": 559,
                    "createdBy": 0,
                    "createdDate": 1315516980000,
                    "updatedBy": 0,
                    "updatedDate": 1321979809000,
                    "lockVersion": 9,
                    "parentAclLevelId": 8476
                  },
                  "isLock": null,
                  "isDefault": false,
                  "createdBy": 0,
                  "createdDate": 1345057196000,
                  "updatedBy": 0,
                  "updatedDate": 1412281715000,
                  "lockVersion": 5,
                  "isActive": true,
                  "homeProject": false,
                  "activateActionAvailable": false,
                  "deactivateActionAvailable": true,
                  "deleteActionAvailable": true,
                  "editActionAvailable": true,
                  "validateEditOnSaveIfNotUsed": false
                },
                "fkChangeOrder": 21358,
                "fkProject": 559,
                "title": "ZOO4-2",
                "referenceNumber": 904,
                "referenceVersion": 1,
                "number": "ZOO4-2",
                "billingSequenceNumber": null,
                "displayStatus": "Active",
                "permissionLevel": "Public",
                "versionStatus": "Master",
                "fkFromCompany": 1,
                "fkFromContact": 345884,
                "fkToCompany": null,
                "changeCreatedDate": 1382504400000,
                "primaryConsultantNumber": null,
                "isScopeChange": false,
                "includeQuotesInSummary": false,
                "externalApproval": false,
                "changePhrase": "",
                "subject": "54655",
                "description": "<p>\n\t56546546</p>\n",
                "estimatedAmount": null,
                "notToExceed": null,
                "requestedByContact": 333862,
                "requestedOnDate": null,
                "submittedByContact": 346031,
                "submittedOnDate": 1382536932000,
                "approvedByContact": null,
                "approvedOnDate": null,
                "comments": null,
                "summaryComments": null,
                "detailsComments": null,
                "createdBy": 100019,
                "createdDate": 1382536932000,
                "updatedBy": 100019,
                "updatedDate": 1384798844000,
                "lockVersion": 6,
                "fkWorkflow": null,
                "workflowStatus": null,
                "displayQuoteAttachments": null,
                "hideBillingline": null,
                "hideBudgetline": null,
                "hideCostAccount": null,
                "hideOverhead": null,
                "hideTaxes": null,
                "insuranceBonding": null,
                "overheadProfitSelfPerformed": 20,
                "overheadProfitSubcontractor": 10,
                "overheadProfitUnassigned": 25,
                "totalAmount": 1100,
                "isAutomaticSCOIssuing": null,
                "homeProject": false,
                "internalChange": false
              },
              "auditLogIDList": [],
              "auditLogParameters": [],
              "isSuperseding": false,
              "isDrawdown": false,
              "distributionAmount": null,
              "ChangeOrderBean": null,
              "projectBean": null,
              "fkFromCompanyBean": null,
              "fkFromContactBean": null,
              "fkToCompanyBean": null,
              "isOverheadProfitSubcontractorUpdated": false,
              "isOverheadProfitSelfPerformedUpdated": false,
              "isOverheadProfitUnassignedUpdated": false,
              "internalChange": false,
              "overheadProfitSubcontractorUpdated": false,
              "overheadProfitSelfPerformedUpdated": false,
              "overheadProfitUnassignedUpdated": false,
              "homeProject": false
            },
            "workflowDocumentDefinitionBean": null,
            "documentWorkflowBean": null,
            "isFromEmail": false,
            "pasteActionPending": false,
            "nbInlineEditing": 0,
            "associatedDocumentLink": null,
            "changeQuoteBeanList": null,
            "changeAttachmentBeanList": null,
            "changeSummaryAttachmentBeanList": null,
            "changeDetailsAttachmentBeanList": null,
            "changeAdditionalCostBeanList": null,
            "changeQuoteBudgetLineBeanList": null,
            "changeDocumentBeanSuperseded": null,
            "workflowBean": null,
            "changeSummaryBean": null,
            "workflowParams": [],
            "changeDistributionBean": null,
            "changeDocumentCostAccountBeanList": null,
            "changeDocumentBudgetLineBeanList": null,
            "changeDocumentBillingBeanList": null,
            "changeQuotesBillingDisplayInSummaryBeanList": null,
            "isDistributionApproved": false,
            "changeDocumentApproved": false,
            "changeSummaryReadOnly": false,
            "commentReadOnly": false,
            "changeDistributionReadOnly": false,
            "changeBillingDistributionReadOnly": false,
            "isNewChangeDocument": false,
            "isRevised": false,
            "isOldNew": false,
            "changeQuoteDetailsBeanSupersededList": null,
            "milestoneLinkBean": null,
            "milestoneLinkBeanToDelete": null,
            "comments": null,
            "isForwardAndExportPDFAvailable": false,
            "revised": false,
            "oldNew": false,
            "newChangeDocument": false,
            "forwardAndExportPDFAvailable": false,
            "distributionApproved": false,
            "homeProject": false,
            "fromEmail": false
          }
        },
        "messsages": [
          {
            "type": "Information",
            "message": "Save successful"
          }
        ]

# Data Structures

## Message (object)

+ type (enum[string]) - Message type.
    + Members
        + Information
        + Warning
        + Error
        + Fatal
+ message: Save successful (string) - The message.

## User Credentials (object)

+ username: root@ellisdon.com (string) - User name
+ authSessionId: 102W6swFEMaTPCjYjRJudvnLg (string) - Authenticated session ID (i.e. Okta session ID)

## Token (object)

+ token: eyJhb.eyJleHBpcnkiO.RQ1cNX (string) - Token representing the user session.  Pass to other requests in the **G3-User-Session-Token** header.

## ACP Request (object)

+ groupName: Comany Category (string) - Check for access to this group.

## ACP Response (object)

+ groupName: Comany Category (string) - Check for access to this group.
+ privilege (enum[string]) - Check if user has this privilege or higher for group name.
    + Members
        + Read
        + Update
        + Create
        + Execute

## Change Type Setting (object)

+ persistentDTO (object)
    + idChangeType: 251902 (number)
    + isActive: true (boolean)
    + name: null (string)
    + description: Architectural Change Order (string)
    + prefix: ACO (string)
    + nextAvailableNumber: 25 (number)
    + isTotalEstimatedAmount: false (boolean)
    + isNotToExceedAmount: false (boolean)
    + updatePrimeContractPayApplication: true (boolean)
    + isDrawdown: true (boolean)
